name: Build with version
on:
  - push

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest    
    outputs:
        version: ${{ steps.version.outputs.version }} 
    steps:
      # Remember we have to check out the repository first!
      - name: Checkout repository
        uses: actions/checkout@v5

      # This step installs the dependencies
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate version
        id: version
        run: |
          VERSION="1.2.3"
          echo "version=$VERSION" >> $GITHUB_OUTPUT        
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      # Remember we have to check out the repository first!
      - name: Checkout repository
        uses: actions/checkout@v5

      # This step installs the dependencies
      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
    
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy version
        run: echo "Deploying version ${{ needs.build.outputs.version }}"
    

